### ISSUE TITLE
Composer for 2.x releases?

### ISSUE THREAD

**Issue by alancwoo** [jonasholfeld/kirby3-many-to-many-field#13]
Can this be updated on packagist for the 2.x releases please? I'm unable to require the latest `2.0.1` version.

`Root composer.json requires jonasholfeld/kirby3-many-to-many-field ^2.0.1, found jonasholfeld/kirby3-many-to-many-field[dev-sortable-structure-bugfix, dev-master, dev-jonasholfeld-patch-1, dev-development, 1.0.0] but it does not match the constraint.`

**Comment by jonasholfeld** [comment]
Fixed via https://github.com/jonasholfeld/kirby3-many-to-many-field/commit/48fb1234b4cbd5a8b24899fdd409a670fcb52b98
