### ISSUE TITLE
Composer doesn't work

### ISSUE THREAD

**Issue by janstieler** [jonasholfeld/kirby3-many-to-many-field#4]
Hi,
if I try to install your plugin with composer it breaks with the following error:
```
[InvalidArgumentException]
  Could not find a matching version of package jonasholfeld/kirby3-many-to-many-field. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).
```
Also I couldn't find your project on packagist. So it looks that you have forget to publish the plugin for composer.
It would be nice if you could added a working composer install possibility!

Cheers

**Comment by jonasholfeld** [comment]
Thanks for the message, indeed I forgot to publish it on packagist. Solved and tested just now - composer install now works.

Cheers!
