### ISSUE TITLE
faster lookup

### ISSUE THREAD

**Issue by bnomei** [jonasholfeld/kirby3-many-to-many-field#5]
instead of using
`$projectPage = page("projects")->children()->findBy("autoid", $project->foreignkey()->value());` a call to `$projectPage = $project->foreignkey()->fromAutoID();` should be a bit faster (but maybe less easy to read).

https://github.com/bnomei/kirby3-autoid/blob/5a35e31437d8f7bfbfe8da7ac7e2d66fadbe1a78/index.php#L120

otherwise great plugin!

**Comment by jonasholfeld** [comment]
yes indeed, Mr. Bnomei! Changed in the Readme.

Thanks for the note and big ups for your great work!
