### ISSUE TITLE
Invalid field type ("relation")

### ISSUE THREAD

**Issue by snau** [jonasholfeld/kirby3-many-to-many-field#6]
I am using the plainkit with no plugins except "kirby3-autoid" and "kirby3-many-to-many-field" and tested it with the example files you provided. I get the error message `Invalid field type ("relation")` inside "work" or "artist" subpage. Same problem with the other blueprint examples.

**Comment by jonasholfeld** [comment]
hi!
yeah, there is a mistake in the artist example, type field has to be "manytomany" instead of "relation". i will change and test this later today, but you can go with the project example that is also documented in the readme.

**Comment by jonasholfeld** [comment]
updated and tested now.

**Comment by snau** [comment]
That did the trick. Thanks.
